config/routes.rb
Mediahaste::Application.routes.draw do

  resources :articles

root :to => "pages#home"

match '/news', :to => "articles#index"
match 'pictures', :to => "pages#pictures"
match '/events', :to => "pages#events"
match '/about', :to => "pages#about" 
 

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :headline, :body, :date
  
  validates :headline, :presence => true,
                       :length => { :maximum => 150 }
  validates :body, :presence => true,
                   :length => { :maximum => 5000 }
                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    @menu_home = "active"
  end

  def news
    @title = "News"
    @menu_news = "active"
  end

  def pictures
    @title = "Pictures"
    @menu_pictures = "active"
  end

  def events
    @title = "Events"
    @menu_events = "active"
  end

  def about
    @title = "About"
    @menu_about = "active"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def title
  base_title = "Media Haste"
  if @title.nil?
    base_title
  else
    "#{base_title} | #{@title}"
  end
end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error">
      <b><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</b><br/>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
	  </ul>
	  </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %><br />
    <%= f.text_field :headline, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :cols => 80, :rows => 40 %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit "Add/Change Article"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles:</h1>

<table>
  <tr>
    <th>Headline</th>
    <th>Body (preview)</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.headline %></td>
    <td><%= article.body[0..100] %>...</td>
    <td><%= article.date %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
 <!-- if there is a notice, display it as class = "notice"  -->
<% if notice != nil %>
<% then %><div id="notice">
	<%= notice %>
</div>
<% end %>

<h1>
  <%= @article.headline %>
</h1> 

 <p class="articledate">
  <%= @article.date %>:  
 </p>


<%= simple_format(@article.body, :class => 'articlebody' ) %>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  
  <%= csrf_meta_tag %>
   <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'  %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
      <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  
</head>
<body>

<div class="container">
	<header>
		
	<%= image_tag("mh_logo.png", :alt => "Sample App", :class => "#", :size => "750x178")%>
		<nav id="roundbar-grey">
          <ul>
            <li class="first <%=@menu_home%>"><%= link_to "Home", root_path %></li>
            <li class="<%=@menu_news%>"><%= link_to "News", news_path %></li>
            <li class="<%=@menu_pictures%>"><%= link_to "Pictures", pictures_path %></li>
            <li class="<%=@menu_events%>"><%= link_to "Events", events_path %></li>
            <li class="last <%=@menu_about%>"><%= link_to "About", about_path %></li>
          </ul>
		</nav>
	    
	</header>

	<div class="section span-17">
		
				<%= yield %>
								
	</div>	
</div>
</body>
</html> 

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/events.html.erb
<h1>Pages#events</h1>
<p>Find me in app/views/pages/events.html.erb</p>

app/views/pages/home.html.erb
<hr>
<h1 class="thinframe"><center> <br>Ad space<br><br> </center></h1>
<hr>


<div class="center-text span-4">  <!-- span-4 is 164px wide -->

<!-- Left column begin -->
	
	<div class="center-text span-4">  
	<%= image_tag("left_ad.png", :alt => "Left Ad", :class => "#", :size => "164x150")%>
	<br><br> 
	</div>
	
	<div class "center-text span-4">
	<p class="small"><i>
		-Generated advertisement<br>
		-Generated advertisement<br>
		-Generated advertisement<br>
    </p>
	</div>
	
	<div class "center-text span-4">
	<p class="small"><i>
		#Link to News Article<br>
		#Link to News Article<br>
		#Link to News Article<br>
	</i></p>
	</div>
	
	
</div>

<div class="span-1"><p></p></div>

<div class="center-text span-7"> <!-- span-7 is 374px wide -->
			
<!-- Center column begin -->
			
	<div class="center-text span-7">		
	<!-- Pulls the featured image from the featured article, thinframe in the interim  -->
	<%= image_tag("Featured.png", :alt => "Featured Article Image", :class => "", :size => "290x150")%>	
	<br><br>
	</div>
	
	<div class="span-7">
		<p class="small justify-text">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eget lacus sed urna cursus tempor. Sed lectus nulla, consectetur vitae venenatis ac, adipiscing nec tortor. Aenean eget justo at leo rhoncus...<span style="font-weight:bold;"> .........#Read more link to featured article </span>	
		</p>
	</div>

	<div class="span-3">
		<p>News 1 con't</p>		
	</div>
	
	<div class="span-1"></div>
	
	<div class="span-3">
		<p>News 2 con't</p>		
	</div>






</div>

<div class="span-1"><p></p></div>

<div class="center-text span-4 last">

<!-- Right column begin -->
	
		<div class="center-text span-4">  
	<%= image_tag("Subfeature.png", :alt => "Left Ad", :class => "#", :size => "164x150")%>
	<br><br> 
	</div>
	
	<div class "center-text span-4">
	<p class="small"><i>
		Morbi eleifend velit quis magna aliquet ultricies. Curabitur mauris magna, semper et tincidunt nec, sagittis ut magna. Cras blandit quam vel augue eleifend. <span style="font-weight:bold;">#Read more</span>
    </p>
	</div>
	
	<div class "center-text span-4">
	<p class="small">
		Weather plugin
	</p>
	</div>
	
	<div class "center-text span-4">
	<p class="small">
		Where we'll be next
	</p>
	</div>
	
	
	
		
</div>

app/views/pages/news.html.erb
<h1>Pages#news</h1>
<p>Find me in app/views/pages/news.html.erb</p>

app/views/pages/pictures.html.erb
<h1>Pages#pictures</h1>
<p>Find me in app/views/pages/pictures.html.erb</p>